services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: puntospoint_store_development
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "rm -f /code/tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/puntospoint_store_development
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/puntospoint_store_development
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8

volumes:
  db-data:
